/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jiangwei_JniTest1 */

#ifndef _Included_com_jiangwei_JniTest1
#define _Included_com_jiangwei_JniTest1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jiangwei_JniTest1
 * Method:    changeFieldFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jiangwei_JniTest1_changeFieldFromC
  (JNIEnv *, jobject);
    
JNIEXPORT void JNICALL Java_com_jiangwei_JniTest1_changeAge
  (JNIEnv *, jobject);
    
JNIEXPORT void JNICALL Java_com_jiangwei_JniTest1_callMethod
  (JNIEnv *, jobject);
    
JNIEXPORT void JNICALL Java_com_jiangwei_JniTest1_callStaticMethod
    (JNIEnv *, jobject);
    
JNIEXPORT jlong JNICALL Java_com_jiangwei_JniTest1_callConstructors
    (JNIEnv *, jobject);
    
JNIEXPORT void JNICALL Java_com_jiangwei_JniTest1_callSuperMethod
    (JNIEnv *, jobject);
    
JNIEXPORT jstring JNICALL Java_com_jiangwei_JniTest1_getString
    (JNIEnv *, jobject, jstring);
    
JNIEXPORT jintArray JNICALL Java_com_jiangwei_JniTest1_sortArray
    (JNIEnv *, jobject, jintArray);
#ifdef __cplusplus
}
#endif
#endif
