/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jiangwei_JniTest1 */

#ifndef _Included_com_jiangwei_JniTest1
#define _Included_com_jiangwei_JniTest1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jiangwei_JniTest1
 * Method:    changeFieldFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jiangwei_JniTest1_changeFieldFromC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
